name: Build Docker image

on:
  push:
jobs:
  docker:
    runs-on: ubuntu-latest

steps:
  - uses: actions/checkout@v1.0
    name: Check out code

  - uses: mr-smithers-excellent/docker-build-push@v3
    name: Build & push Docker image

  - uses: docker/login-action@v2
    name: login to docker Hub
    with:
      image: kdua1/may-image
      tags: v1, latest
      registry: dockerfile.io
      dockerfile: Dockerfile
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}